<tr>
	<td>
		<a href="<?php echo $this->url(array('action'=>'preparationDetail', 'pid'=>$this->RequirementID)); ?>">
			<?php echo $this->escape($this->RequirementID); ?>
		</a>
	</td>
	<td><?php echo $this->escape($this->Status); ?></td>
	<td><?php echo $this->escape($this->Priority); ?></td>
	<td><?php echo $this->escape($this->Product); ?></td>
	<td><?php echo $this->escape($this->Country); ?></td>
</tr>
