<?php
// HighRoller: include class files
 require_once('HighRoller_1.0.5/HighRoller.php');
 require_once('HighRoller_1.0.5/HighRollerSeriesData.php');
 require_once('HighRoller_1.0.5/HighRollerColumnChart.php');
 //require_once 'Zend/Application.php';
 
 $columnchart = new HighRollerColumnChart();
 $columnchart->title->text = 'Column Chart';
 $columnchart->yAxis->title->text = 'Preparation';
 $columnchart->yAxis->stackLabels->enabled = true;
 $columnchart->chart->renderTo ='container';
 $columnchart->plotOptions->column->stacking = 'normal';

 $columnchart->xAxis->categories = array('Preparation');
 
 foreach ($this->statuslist as $status) :
 	$series = new HighRollerSeriesData();
	$series->addName($this->escape($status['Status']))->addData(array(intval($this->escape($status['Amount']))));
	$columnchart->addSeries($series);
 endforeach;
?>


<script type="text/javascript">
  $(document).ready(function(){
    <?php echo $columnchart->renderChart()?>
  });
</script>

<div class="well">
	<?php if($this->statuslist) : ?>
		<?php foreach ($this->statuslist as $status) : ?>
			[<?php echo $this->escape($status['Status']); ?>]
			<?php echo $this->escape($status['Amount']); ?><br />
		<?php endforeach; ?>
	<?php else : ?>
		<div class="alert">Konnte Status-List nicht lesen :-(</div>
	<?php endif; ?>
</div>

<div id="container"></div>
